---
name: Tests and Checks (Full)

on:
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci
  TERM: ansi

jobs:
  bootstrap:
    name: Bootstrap environment
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache.outputs.path }}
      cache-key: ${{ steps.cache.outputs.key }}
    env:
      JUST_TAG: 1.24.0
    steps:
      - name: Build cache params
        id: cache
        run: |
          echo "path=$CACHE_PATH" >> "$GITHUB_OUTPUT"
          echo "$KEY_INPUT" | md5sum | awk '{print $1}' | xargs -I% echo "key=cargobin-%-${RUNNER_OS}" >> "$GITHUB_OUTPUT"
        env:
          CACHE_PATH: |
            ~/.cargo/bin/
          KEY_INPUT: |
            just:${{env.JUST_TAG}}

      - uses: actions/cache@v4
        id: get-cache
        with:
          path: ${{ steps.cache.outputs.path }}
          key: ${{ steps.cache.outputs.key }}

      - name: Install just
        run: cargo install "just@$JUST_TAG"
        if: steps.get-cache.outputs.cache-hit != 'true'

  foundry:
    name: Foundry project (full)
    runs-on: ubuntu-latest
    needs: bootstrap
    if: ${{ github.head_ref == 'develop' }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set FOUNDRY_VERSION
        run: echo "FOUNDRY_VERSION=$(head .foundryref)" >> "$GITHUB_ENV"

      - uses: actions/cache@v4
        with:
          path: ${{ needs.bootstrap.outputs.cache-path }}
          key: ${{ needs.bootstrap.outputs.cache-key }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: just deps

      - name: Build
        run: just build --sizes

      - name: Run unit-tests
        run: just test-unit

      - name: Run tests for current CSM state on fork
        run: just test-csm-current
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      # TODO: Enable later after mainnet deployment
      # - name: Run tests for current Curated state on fork
      #   run: just test-curated-current
      #   env:
      #     CHAIN: mainnet
      #     RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      # TODO: Enable later after mainnet deployment
      # - name: Run tests for current CSM0x02 state on fork
      #   run: just test-csm0x02-current
      #   env:
      #     CHAIN: mainnet
      #     RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local deployment tests for CSM v3 deploy
        run: just test-csm-v3-only-deploy
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local deployment tests for CSM scratch deploy
        run: just test-csm-full-deploy
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local deployment tests for Curated scratch deploy
        run: just test-curated-full-deploy
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local deployment tests for CSM0x02 scratch deploy
        run: just test-csm0x02-full-deploy
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local integration tests for CSM deployment
        run: just test-csm-local
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local integration tests for Curated deployment
        run: just test-curated-local
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run local integration tests for CSM0x02 deployment
        run: just test-csm0x02-local
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Run post-vote tests after CSM v3 upgrade
        run: just test-csm-upgrade
        env:
          CHAIN: mainnet
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}
